"""add document metadata

Revision ID: 09a13f83b822
Revises: 046cfe9be287
Create Date: 2026-10-01 00:14:36.228934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a13f83b822'
down_revision: Union[str, Sequence[str], None] = '046cfe9be287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=1000), nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('modified_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'modified_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
